import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/custom/navbar';

const inter = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen bg-black text-sky-50">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
